In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
sns.set_style('whitegrid')
%matplotlib inline

In [2]:
DA=pd.read_csv('Dataset A.csv')

In [3]:
DA

Name                       Email ID  Phone Number  \
0    Michael Stefenson      mstephenson@fernandez.com    3028039388   
1        Hershal Stark              hduke@hotmail.com    9089646263   
2           Allen Paul               pallen@yahoo.com    7071678287   
3      Rebecca Ganguly        riverarebecca@gmail.com    3343675411   
4        Stefen Potter  mstephens@davidson-herman.com    3760942236   
..                 ...                            ...           ...   
495      Jessica Lewis   lewisjessica@craig-evans.com    2938951583   
496       Katrina Kaif            katrina56@gmail.com    1810163196   
497         Dale Stein             dale88@hotmail.com    2751936173   
498  Christofer Wilson            cwilson@hotmail.com    5175585593   
499      Hannah Wilson      hannahwilson@davidson.com    8332497042   

     Average Time on App (Minutes/Day)  Total Purchase from App (Rupees/year)  \
0                            21.297837                                   4492   
1                            20.860382                                   2077   
2                            25.778359                                   6254   
3                            23.383813                                   3247   
4                            23.771715                                   7708   
..                                 ...                                    ...   
495                          29.478367                                    201   
496                          25.152565                                   1374   
497                          26.412986                                   8490   
498                          25.703370                                   9243   
499                          23.863669                                   8194   

     Average Time on Website (Minutes/Day)  \
0                                11.526953   
1                                18.438460   
2                                17.973034   
3                                16.101074   
4                                14.728785   
..                                     ...   
495                              10.217509   
496                              19.751357   
497                              19.897084   
498                              12.821889   
499                              19.677405   

     Total Purchase from Website (Rupees/year)  Length of Membership (Year)  \
0                                         6403                     4.082621   
1                                         4675                     2.664034   
2                                         1640                     4.104543   
3                                         8091                     3.120179   
4                                          274                     4.446308   
..                                         ...                          ...   
495                                       8526                     3.746573   
496                                       2950                     3.576526   
497                                       7827                     4.958264   
498                                        845                     2.336485   
499                                       6095                     2.735160   

     Yearly Amount Spent (Minutes/year)  \
0                           6564.958054   
1                           7859.768360   
2                           8750.278491   
3                           7896.977495   
4                           7700.100022   
..                                  ...   
495                         7939.175212   
496                         8980.784423   
497                         9262.013901   
498                         7705.051722   
499                         8708.214811   

     Total Purchase of each customer (Rupees/year)  \
0                                            10895   
1                                             6752   
2          

In [4]:
DA.describe()

Phone Number  Average Time on App (Minutes/Day)  \
count  5.000000e+02                         500.000000   
mean   5.469654e+09                          24.929437   
std    2.612551e+09                           2.909053   
min    1.053311e+09                          20.008966   
25%    3.208662e+09                          22.240235   
50%    5.354163e+09                          24.897305   
75%    7.768053e+09                          27.519510   
max    9.969679e+09                          29.997169   

       Total Purchase from App (Rupees/year)  \
count                             500.000000   
mean                             4756.140000   
std                              2804.249391   
min                               102.000000   
25%                              2403.750000   
50%                              4644.500000   
75%                              7159.000000   
max                              9935.000000   

       Average Time on Website (Minutes/Day)  \
count                             500.000000   
mean                               14.963452   
std                                 2.876747   
min                                10.031415   
25%                                12.330589   
50%                                14.930876   
75%                                17.502808   
max                                19.984770   

       Total Purchase from Website (Rupees/year)  Length of Membership (Year)  \
count                                  500.00000                   500.000000   
mean                                  4868.54000                     3.533462   
std                                   2979.57251                     0.999278   
min                                    119.00000                     0.269901   
25%                                   2241.75000                     2.930450   
50%                                   4762.00000                     3.533975   
75%                                   7631.00000                     4.126502   
max                                   9958.00000                     6.922689   

       Yearly Amount Spent (Minutes/year)  \
count                          500.000000   
mean                          7978.577906   
std                            837.253306   
min                           6103.259974   
25%                           7388.705017   
50%                           7983.092202   
75%                           8517.869934   
max                           9799.336650   

       Total Purchase of each customer (Rupees/year)  \
count                                     500.000000   
mean                                     9624.680000   
std                                      4038.452321   
min                                       973.000000   
25%                                      6712.500000   
50%                                      9817.000000   
75%                                     12532.250000   
max                                     19508.000000   

       Ratings given by customer (Out of 5)  
count                            500.000000  
mean                               3.954000  
std                                0.825377  
min                                3.000000  
25%                                3.000000  
50%                                4.000000  
75%                                5.000000  
max                                5.000000

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X=DA[['Total Purchase from App (Rupees/year)','Total Purchase from Website (Rupees/year)','Average Time on App (Minutes/Day)','Average Time on Website (Minutes/Day)','Length of Membership (Year)','Yearly Amount Spent (Minutes/year)','Total Purchase of each customer (Rupees/year)']]
y=DA['Ratings given by customer (Out of 5)']

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=25)

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [10]:
predictions = logmodel.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix

In [12]:
print(confusion_matrix(y_test, predictions))

[[30  5 12]
 [22  7  9]
 [28  6  6]]


In [13]:
from sklearn.metrics import classification_report

In [14]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           3       0.38      0.64      0.47        47
           4       0.39      0.18      0.25        38
           5       0.22      0.15      0.18        40

    accuracy                           0.34       125
   macro avg       0.33      0.32      0.30       125
weighted avg       0.33      0.34      0.31       125

